name: 'unlock.terraform.state'

on:
  workflow_dispatch:
   inputs:
      lock-id:
        description: "Lock Id"
        type: string
        required: true
        
      stage:
        type: choice
        description: stage to run
        options: 
        - test
        - preprod
        required: true
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true
jobs:
  Plan:
    name: Unlock
    runs-on: ubuntu-latest
    environment: test
    timeout-minutes: 720
    env:
      ARM_CLIENT_ID: ${{ secrets.AZ_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZ_CLIENT_SECRET }}
      ARM_TENANT_ID: ${{ secrets.AZ_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZ_SUBSCRIPTION_ID }}
      STATESTORAGE: iaccode
      STATECONTAINER: states
      STATERG: rg-infra
    defaults:
      run:
        shell: bash

    steps:

    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
   
    - name: Terraform Init
      working-directory: ./Test
      run: terraform init  -backend-config=key="test.tfstate"
        
    - name: Terraform Unlock
      if: ${{inputs.stage=='test'}}
      working-directory: ./Test
      run: terraform force-unlock -force ${{ inputs.lock-id }}
