name: 'unlock.terraform.state'

on:
  workflow_dispatch:
   inputs:
      lock-id:
        description: "Lock Id"
        type: string
        required: false
        default: '6638e010-8fb0-46cf-ahma-21e806602f3a'
      stage:
        type: choice
        description: stage to run
        options: 
        - test
        - preprod
        required: true
jobs:
 build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: greet
        run: | 
          echo "stage is ${{ github.event.inputs.stage }} / ${{ inputs.stage }}"
          echo "choice is ${{ github.event.inputs.lock-id }}" / ${{ inputs.lock-id }}