name: 'unlock.terraform.state'

on:
  workflow_dispatch:
   inputs:
      lock-id:
        description: "Lock Id"
        type: string
        required: true
        
      stage:
        type: choice
        description: stage to run
        options: 
        - test
        - preprod
        required: true
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true
jobs:
  Plan:
    name: Unlock
    runs-on: ubuntu-latest
    environment: ${{inputs.environment}}
    timeout-minutes: 720
    env:
      ARM_CLIENT_ID: ${{ secrets.AZ_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZ_CLIENT_SECRET }}
      ARM_TENANT_ID: ${{ secrets.AZ_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZ_SUBSCRIPTION_ID }}
      state-file : "test.tfstate"
    defaults:
      run:
        shell: bash

    steps:

    - name: Checkout
      uses: actions/checkout@v3
    - name: Set Sate file
      run: |
       if($env=="test"){
         ECHO "state-file=ahmar"
         }
    - name: Send greeting
      run: echo "${{ env.state-file }}"
    - name: Unlock
      uses: ./.github/actions/Terraform
      with:
           state-file: "test.tfstate"
           lock-id: "${{ inputs.lock-id }}"
           working-directory: ./Test
   
    
